name = "mochi_apq"
version = "0.1.0"
description = "Automatic Persisted Queries (APQ) for mochi GraphQL"
licences = ["Apache-2.0"]
repository = { type = "github", user = "qwexvf", repo = "mochi" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_crypto = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
